version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    volumes:
      - mongodb_/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: